ProyectoDjango/ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
]

ProyectoDjango/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.Blog, name="Blog"),
    path('categoria/<int:id_categorias>/', views.Categorias, name="Categorias"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjango/carro/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjango/tienda/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.Tienda, name="Tienda"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjango/tienda/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seccion(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    secciones=models.ForeignKey(Seccion, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

ProyectoDjango/tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.


def Tienda(request):
    productos=Producto.objects.all()
    return render(request, "tienda/Tienda.html", {"productos": productos})

ProyectoDjango/tienda/templates/tienda/Tienda.html
<html>
    <head>
        Tienda
    </head>

    <body>
        <div>
            <div>
                <p>IMPORTE TOTAL: {{importe_total_carro}}</p>
                <div>
                    {% include "carro/widget.html" %}
                </div>
            </div>
            {% for producto in productos %}
            <div>
                <div>
                    <img src="{{producto.imagen.url}}"/>
                </div>
                <h7>{{producto.nombre}}</h7>
                <p>{{producto.precio}}</p>
                <a href="{% url 'carro:agregar' producto.id %}">AGREGAR PRODUCTO</a>
            </div>
            {% endfor %}
        </div>
    </body>
</html>